-- Supabase SQL for Antique Chat System

-- Create antique_chat_messages table
CREATE TABLE IF NOT EXISTS antique_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (optional, for demo you can leave it off or enable for public access)
ALTER TABLE antique_chat_messages ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read messages
CREATE POLICY "Public read messages" ON antique_chat_messages
    FOR SELECT USING (true);

-- Allow anyone to send messages
CREATE POLICY "Public insert messages" ON antique_chat_messages
    FOR INSERT WITH CHECK (true);

-- Allow anyone to delete messages (or restrict to sender if you add user auth)
CREATE POLICY "Public delete messages" ON antique_chat_messages
    FOR DELETE USING (true);

-- Grant permissions
GRANT ALL ON antique_chat_messages TO anon, authenticated;
